/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ds' at '17. 1. 10 오후 5:48' with Gradle 2.14.1
 *
 * @author ds, @date 17. 1. 10 오후 5:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
